name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run specific test file
        # Directly point to your test file
        run: npx jest src/app.test.js

      - name: Build application
        run: npm run build || echo "No build step"

        -name: Build docker image
        uses:  actions/build-push-actions@v2
        with: 
          context:
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.docker_username}}/CI-CD-assignment:latest
        -name: Login  to Docker Hub
        uses: docker/Login-actions@v1
        with:
          username: ${{secrets.docker_username}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

        -name: Push to Docker Hub
        uses: actions/build-push-action@v2
        with: 
          context:
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.docker_username}}/CI-CD-assignment:latest
        




